complete -c tmplt -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c tmplt -n "__fish_use_subcommand" -f -a "new" -d 'Create a new project'
complete -c tmplt -n "__fish_use_subcommand" -f -a "init" -d 'Create a new template'
complete -c tmplt -n "__fish_use_subcommand" -f -a "import" -d 'Import a template'
complete -c tmplt -n "__fish_use_subcommand" -f -a "list" -d 'List all templates'
complete -c tmplt -n "__fish_use_subcommand" -f -a "remove" -d 'Remove a template'
complete -c tmplt -n "__fish_use_subcommand" -f -a "version" -d 'Show version'
complete -c tmplt -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c tmplt -n "__fish_seen_subcommand_from new" -s h -l help -d 'Print help'
complete -c tmplt -n "__fish_seen_subcommand_from init" -s h -l help -d 'Print help'
complete -c tmplt -n "__fish_seen_subcommand_from import" -s h -l help -d 'Print help'
complete -c tmplt -n "__fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c tmplt -n "__fish_seen_subcommand_from remove" -s h -l help -d 'Print help'
complete -c tmplt -n "__fish_seen_subcommand_from version" -s h -l help -d 'Print help'
complete -c tmplt -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from new; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from import; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from help" -f -a "new" -d 'Create a new project'
complete -c tmplt -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from new; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from import; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from help" -f -a "init" -d 'Create a new template'
complete -c tmplt -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from new; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from import; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from help" -f -a "import" -d 'Import a template'
complete -c tmplt -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from new; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from import; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List all templates'
complete -c tmplt -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from new; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from import; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from help" -f -a "remove" -d 'Remove a template'
complete -c tmplt -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from new; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from import; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from help" -f -a "version" -d 'Show version'
complete -c tmplt -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from new; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from import; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
